# Generated by Django 4.1.4 on 2022-12-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_players_addedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='addedBy',
        ),
    ]
